version: "3"

includes:
  common: ./build/Taskfile.yml
  windows: ./build/windows/Taskfile.yml
  darwin: ./build/darwin/Taskfile.yml
  linux: ./build/linux/Taskfile.yml

vars:
  APP_NAME: "ms-exp-tracker"
  BIN_DIR: "bin"
  VITE_PORT: "{{.WAILS_VITE_PORT | default 9245}}"

tasks:
  build:
    summary: Builds the application
    cmds:
      - task: "{{OS}}:build"

  package:
    summary: Packages a production build of the application
    cmds:
      - task: "{{OS}}:package"

  run:
    summary: Runs the application
    cmds:
      - task: "{{OS}}:run"

  dev:
    summary: Runs the application in development mode
    cmds:
      - wails3 dev -config ./build/config.yml -port {{.VITE_PORT}}

  tidy:
    summary: Formats .go files and tidies dependencies
    cmds:
      - go fmt ./...
      - go mod tidy

  audit:
    summary: Runs quality control checks
    cmds:
      - echo 'Checking module dependencies'
      - go mod tidy -diff
      - go mod verify
      - echo 'Vetting code...'
      - go vet ./...
      - staticcheck ./...
      - echo 'Running tests...'
      - go test -race -vet=off ./...

  test:
    summary: Runs tests
    cmds:
      - go test ./...

  tesseract:
    summary: Builds tesseract binary
    cmds:
      - echo 'Deleting tesseract binary from current folder...'
      - rm -rf ./tesseract
      - echo 'Bringing up Docker Container...'
      - docker compose -f docker-compose-tesseract.yml up -d
      - echo 'Copying Built Tesseract Binary...'
      - docker cp `docker compose -f docker-compose-tesseract.yml ps -q tesseract`:/tesseract-5.5.0/tesseract .
      - echo 'Killing Container...'
      - docker compose -f docker-compose-tesseract.yml kill
      - echo 'Taking Container Down...'
      - docker compose -f docker-compose-tesseract.yml down
      - echo 'Done building static Tesseract binary!'
